# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  database: score-demo
  pool: 5
  username: root
  password: ~
  host: localhost

development:
  <<: *default

test:
  <<: *default
  # database: db/test.sqlite3

production:
  <<: *default
  # database: db/production.sqlite3
